### ISSUE TITLE
After installing firebase-functions-test as a dev dependency TypeError [ERR_INVALID_ARG_VALUE]

### ISSUE THREAD

**Issue by nuwanarti** [serdaraglamis/firebase-nodejs-starter#2]
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
    at Module.require (internal/modules/cjs/loader.js:634:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at InitializeFirebaseAdminStubs (/Users/rt/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:231:18)
    at /Users/rt/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:451:9
    at Generator.next (<anonymous>)
    at /Users/rt/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/rt/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
    at main (/Users/rt/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:421:12)
    at Object.<anonymous> (/Users/rt/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:511:5)
⚠  Your function was killed because it raised an unhandled error.
127.0.0.1 - - [01/Oct/2019:22:52:13 +0000] "GET /favicon.ico HTTP/1.1" 500 1087 "http://localhost:5000/hi" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

There is this error

**Comment by nuwanarti** [comment]
This error will go away after installing grpc

npm install grpc
